package resource

var AssetsList = []string{
	"/dist/css/all.min.css",
	"/dist/css/blue.png",
	"/dist/css/blue@2x.png",
	"/dist/css/fonts/6xK3dSBYKcSV-LCoeQqfX1RYOo3qOK7g.ttf",
	"/dist/css/fonts/6xKydSBYKcSV-LCoeQqfX1RYOo3i54rwlxdr.ttf",
	"/dist/css/fonts/6xKydSBYKcSV-LCoeQqfX1RYOo3ig4vwlxdr.ttf",
	"/dist/css/fonts/6xKydSBYKcSV-LCoeQqfX1RYOo3ik4zwlxdr.ttf",
	"/dist/fonts/6xK1dSBYKcSV-LCoeQqfX1RYOo3qPZ7nsDc.ttf",
	"/dist/fonts/6xKwdSBYKcSV-LCoeQqfX1RYOo3qPZY4lCds18E.ttf",
	"/dist/fonts/6xKwdSBYKcSV-LCoeQqfX1RYOo3qPZZMkids18E.ttf",
	"/dist/fonts/FontAwesome.otf",
	"/dist/fonts/fontawesome-webfont.eot",
	"/dist/fonts/fontawesome-webfont.svg",
	"/dist/fonts/fontawesome-webfont.ttf",
	"/dist/fonts/fontawesome-webfont.woff",
	"/dist/fonts/fontawesome-webfont.woff2",
	"/dist/fonts/glyphicons-halflings-regular.eot",
	"/dist/fonts/glyphicons-halflings-regular.svg",
	"/dist/fonts/glyphicons-halflings-regular.ttf",
	"/dist/fonts/glyphicons-halflings-regular.woff",
	"/dist/fonts/glyphicons-halflings-regular.woff2",
	"/dist/fonts/ionicons.ttf",
	"/dist/fonts/ionicons.woff",
	"/dist/img/avatar04.png",
	"/dist/js/all.min.js",
	"/dist/js/all_2.min.js",
	"/dist/js/chart.js",
	"/dist/js/fontawesome-iconpicker.min.js",
	"/dist/js/form.min.js",
	"/dist/js/html5shiv.min.js",
	"/dist/js/respond.min.js",
}
